package com.toabea.closet.product;
import com.toabea.closet.common.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/products") public class ProductController { private final ProductRepository repo; public ProductController(ProductRepository r){repo=r;} @GetMapping("/public") public List<Product> publicProducts(){return repo.findByActiveTrueOrderByCreatedAtDesc();} @GetMapping public List<Product> all(){return repo.findAll();} @PostMapping public ResponseEntity<Product> create(@Valid @RequestBody ProductRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(save(new Product(),r));} @PutMapping("/{id}") public Product update(@PathVariable String id,@Valid @RequestBody ProductRequest r){return save(repo.findById(id).orElseThrow(),r);} @DeleteMapping("/{id}") public void delete(@PathVariable String id){repo.deleteById(id);} private Product save(Product p,ProductRequest r){p.setName(r.name());p.setCategory(r.category());p.setDescription(r.description());p.setPrice(r.price());p.setCompareAtPrice(r.compareAtPrice());p.setImageUrl(r.imageUrl());p.setImageUrls(r.imageUrls()==null?List.of():r.imageUrls());p.setBadge(r.badge());
  List<Product.ProductSize> sizes=r.sizes()==null?List.of():r.sizes().stream().filter(s->s.size()!=null&&!s.size().isBlank()).map(s->new Product.ProductSize(s.size().trim(),Math.max(0,s.stock()))).toList();
  p.setSizes(sizes);
  p.setStock(sizes.isEmpty()?r.stock():sizes.stream().mapToInt(Product.ProductSize::getStock).sum());
  p.setActive(r.active());p.setUpdatedAt(Instant.now());return repo.save(p);}
public record SizeInput(@NotBlank @Size(max=20) String size,@PositiveOrZero int stock){}
public record ProductRequest(@NotBlank @Size(max=120) String name,@NotBlank @Size(max=60) String category,@NotNull @PositiveOrZero BigDecimal price,BigDecimal compareAtPrice,@Size(max=2000) String description,@Size(max=500) String imageUrl,List<@Size(max=500) String> imageUrls,@Size(max=20) String badge,@PositiveOrZero int stock,boolean active,List<SizeInput> sizes){} }
